apiVersion: 1
datasources:
  - name: Napas PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: napas
    secureJsonData:
      password: napas
    jsonData:
      database: napas
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
